# Generated by Django 5.0.1 on 2024-02-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
